/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as DoctorsLawyerIdRouteImport } from './routes/doctors.$lawyerId'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminServiceSectionsRouteImport } from './routes/admin/service-sections'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHolidaysRouteImport } from './routes/admin/holidays'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminAvailabilityRouteImport } from './routes/admin/availability'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminAboutUsRouteImport } from './routes/admin/about-us'
import { Route as AdminServiceSectionsSectionIdRouteImport } from './routes/admin/service-sections.$sectionId'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ServicesRoute,
} as any)
const DoctorsLawyerIdRoute = DoctorsLawyerIdRouteImport.update({
  id: '/$lawyerId',
  path: '/$lawyerId',
  getParentRoute: () => DoctorsRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceSectionsRoute = AdminServiceSectionsRouteImport.update({
  id: '/admin/service-sections',
  path: '/admin/service-sections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHolidaysRoute = AdminHolidaysRouteImport.update({
  id: '/admin/holidays',
  path: '/admin/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/admin/availability',
  path: '/admin/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutUsRoute = AdminAboutUsRouteImport.update({
  id: '/admin/about-us',
  path: '/admin/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceSectionsSectionIdRoute =
  AdminServiceSectionsSectionIdRouteImport.update({
    id: '/$sectionId',
    path: '/$sectionId',
    getParentRoute: () => AdminServiceSectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/staff': typeof StaffRoute
  '/admin/about-us': typeof AdminAboutUsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/service-sections': typeof AdminServiceSectionsRouteWithChildren
  '/admin/services': typeof AdminServicesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/doctors/$lawyerId': typeof DoctorsLawyerIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/service-sections/$sectionId': typeof AdminServiceSectionsSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/staff': typeof StaffRoute
  '/admin/about-us': typeof AdminAboutUsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/service-sections': typeof AdminServiceSectionsRouteWithChildren
  '/admin/services': typeof AdminServicesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/doctors/$lawyerId': typeof DoctorsLawyerIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/service-sections/$sectionId': typeof AdminServiceSectionsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/staff': typeof StaffRoute
  '/admin/about-us': typeof AdminAboutUsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/service-sections': typeof AdminServiceSectionsRouteWithChildren
  '/admin/services': typeof AdminServicesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/doctors/$lawyerId': typeof DoctorsLawyerIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/service-sections/$sectionId': typeof AdminServiceSectionsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/services'
    | '/staff'
    | '/admin/about-us'
    | '/admin/appointments'
    | '/admin/availability'
    | '/admin/doctors'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/holidays'
    | '/admin/login'
    | '/admin/service-sections'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/doctors/$lawyerId'
    | '/services/$serviceSlug'
    | '/admin/'
    | '/admin/service-sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/services'
    | '/staff'
    | '/admin/about-us'
    | '/admin/appointments'
    | '/admin/availability'
    | '/admin/doctors'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/holidays'
    | '/admin/login'
    | '/admin/service-sections'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/doctors/$lawyerId'
    | '/services/$serviceSlug'
    | '/admin'
    | '/admin/service-sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/services'
    | '/staff'
    | '/admin/about-us'
    | '/admin/appointments'
    | '/admin/availability'
    | '/admin/doctors'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/holidays'
    | '/admin/login'
    | '/admin/service-sections'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/doctors/$lawyerId'
    | '/services/$serviceSlug'
    | '/admin/'
    | '/admin/service-sections/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  StaffRoute: typeof StaffRoute
  AdminAboutUsRoute: typeof AdminAboutUsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHolidaysRoute: typeof AdminHolidaysRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminServiceSectionsRoute: typeof AdminServiceSectionsRouteWithChildren
  AdminServicesRoute: typeof AdminServicesRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/doctors/$lawyerId': {
      id: '/doctors/$lawyerId'
      path: '/$lawyerId'
      fullPath: '/doctors/$lawyerId'
      preLoaderRoute: typeof DoctorsLawyerIdRouteImport
      parentRoute: typeof DoctorsRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-sections': {
      id: '/admin/service-sections'
      path: '/admin/service-sections'
      fullPath: '/admin/service-sections'
      preLoaderRoute: typeof AdminServiceSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/holidays': {
      id: '/admin/holidays'
      path: '/admin/holidays'
      fullPath: '/admin/holidays'
      preLoaderRoute: typeof AdminHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/admin/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about-us': {
      id: '/admin/about-us'
      path: '/admin/about-us'
      fullPath: '/admin/about-us'
      preLoaderRoute: typeof AdminAboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-sections/$sectionId': {
      id: '/admin/service-sections/$sectionId'
      path: '/$sectionId'
      fullPath: '/admin/service-sections/$sectionId'
      preLoaderRoute: typeof AdminServiceSectionsSectionIdRouteImport
      parentRoute: typeof AdminServiceSectionsRoute
    }
  }
}

interface DoctorsRouteChildren {
  DoctorsLawyerIdRoute: typeof DoctorsLawyerIdRoute
}

const DoctorsRouteChildren: DoctorsRouteChildren = {
  DoctorsLawyerIdRoute: DoctorsLawyerIdRoute,
}

const DoctorsRouteWithChildren =
  DoctorsRoute._addFileChildren(DoctorsRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface AdminServiceSectionsRouteChildren {
  AdminServiceSectionsSectionIdRoute: typeof AdminServiceSectionsSectionIdRoute
}

const AdminServiceSectionsRouteChildren: AdminServiceSectionsRouteChildren = {
  AdminServiceSectionsSectionIdRoute: AdminServiceSectionsSectionIdRoute,
}

const AdminServiceSectionsRouteWithChildren =
  AdminServiceSectionsRoute._addFileChildren(AdminServiceSectionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRouteWithChildren,
  StaffRoute: StaffRoute,
  AdminAboutUsRoute: AdminAboutUsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHolidaysRoute: AdminHolidaysRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminServiceSectionsRoute: AdminServiceSectionsRouteWithChildren,
  AdminServicesRoute: AdminServicesRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
